# Generated by Django 2.2.5 on 2019-10-17 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0002_auto_20191017_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 11, 37, 38, 390197, tzinfo=utc)),
        ),
    ]
