# Generated by Django 2.2.5 on 2019-10-18 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0003_auto_20191017_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='branch',
            field=models.CharField(choices=[('PHY', 'Physics'), ('Chemistry', 'CHEM'), ('Mathematics', 'MATH'), ('B.Sc.(IT)', 'B.Sc.(IT)'), ('Power Electronics & Instrumentation Engineering', 'PEIE'), ('Electronics & Telecommunication Engineering', 'ETE'), ('Civil Engineering', 'CE'), ('Mechanical Engineering', 'ME')], default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 10, 18, 7, 3, 27, 448145, tzinfo=utc)),
        ),
    ]
