# Generated by Django 2.2.5 on 2019-10-18 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0004_auto_20191018_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 10, 18, 7, 4, 43, 914884, tzinfo=utc)),
        ),
    ]
