# Generated by Django 2.2.5 on 2019-10-21 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0005_auto_20191018_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='branch',
            field=models.CharField(choices=[('Physics', 'PHY'), ('Chemistry', 'CHEM'), ('Mathematics', 'MATH'), ('B.Sc.(IT)', 'B.Sc.(IT)'), ('Power Electronics & Instrumentation Engineering', 'PEIE'), ('Electronics & Telecommunication Engineering', 'ETE'), ('Civil Engineering', 'CE'), ('Mechanical Engineering', 'ME')], default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 10, 21, 8, 18, 8, 574451, tzinfo=utc)),
        ),
    ]
