# Generated by Django 2.2.5 on 2019-10-21 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0007_auto_20191021_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(choices=[('Bachelor of Science', 'B.Sc.'), ('Bachelor of Science in Information Technology', 'B.Sc.(IT)'), ('Master of Science', 'M.Sc.'), ('Bachelor of Engineering', 'B.E.'), ('PhD', 'PhD')], default='NULL', max_length=100)),
                ('dept_short', models.CharField(default='NULL', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 10, 21, 11, 18, 59, 942828, tzinfo=utc)),
        ),
    ]
