# Generated by Django 2.2.5 on 2019-10-21 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0008_auto_20191021_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 10, 21, 11, 19, 59, 846684, tzinfo=utc)),
        ),
    ]
