# Generated by Django 2.2.5 on 2019-10-21 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0009_auto_20191021_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
