# Generated by Django 2.2.5 on 2019-10-23 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0011_signininfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signininfo',
            name='new_timestamp',
        ),
        migrations.RemoveField(
            model_name='signininfo',
            name='old_timestamp',
        ),
        migrations.AddField(
            model_name='signininfo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='signininfo',
            name='client_ip',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
