# Generated by Django 2.2.5 on 2019-10-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0012_auto_20191024_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(choices=[('Bachelor of Science', 'B.Sc.'), ('Bachelor of Science in Information Technology', 'B.Sc.(IT)'), ('Master of Science', 'M.Sc.'), ('Bachelor of Engineering', 'B.E.'), ('PhD', 'PhD')], default='NULL', max_length=100, unique=True),
        ),
    ]
