# Generated by Django 2.2.5 on 2019-10-31 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0014_auto_20191030_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='depertment',
        ),
    ]
