# Generated by Django 2.2.5 on 2019-10-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0018_auto_20191101_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='students',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Branch'),
        ),
        migrations.AlterField(
            model_name='students',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
    ]
