# Generated by Django 2.2.5 on 2019-11-01 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0019_auto_20191101_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='depertment',
        ),
        migrations.AddField(
            model_name='branch',
            name='depertment',
            field=models.ManyToManyField(to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='students',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
    ]
