# Generated by Django 2.2.5 on 2019-11-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0020_auto_20191101_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='admission_year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='branch',
            name='depertment',
            field=models.ManyToManyField(to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='students',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
    ]
