# Generated by Django 2.2.5 on 2019-11-12 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0024_auto_20191107_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='odd_semester_fees',
            name='branch',
            field=models.ManyToManyField(to='jist_api.Branch'),
        ),
        migrations.AddField(
            model_name='odd_semester_fees',
            name='semester',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='depertment',
            field=models.ManyToManyField(to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='odd_semester_fees',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='students',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
    ]
