# Generated by Django 2.2.5 on 2019-11-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0027_auto_20191112_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='depertment',
            field=models.ManyToManyField(to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='semester_fees',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='students',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.CreateModel(
            name='be_fee_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Even', 'EVEN'), ('Odd', 'ODD')], default='NULL', max_length=100)),
                ('govt_dues', models.IntegerField(default=0)),
                ('identity_fee', models.IntegerField(default=0)),
                ('examination_fee', models.IntegerField(default=0)),
                ('student_union_fee', models.IntegerField(default=0)),
                ('game_sports_fee', models.IntegerField(default=0)),
                ('magazine_fee', models.IntegerField(default=0)),
                ('laboratory_fee', models.IntegerField(default=0)),
                ('university_registration_fee', models.IntegerField(default=0)),
                ('enrolment_fee', models.IntegerField(default=0)),
                ('electricity_fee', models.IntegerField(default=0)),
                ('group_insurance_fee', models.IntegerField(default=0)),
                ('scout_guide_fee', models.IntegerField(default=0)),
                ('internet_fee', models.IntegerField(default=0)),
                ('welfare_fee', models.IntegerField(default=0)),
                ('development_fee', models.IntegerField(default=0)),
                ('library_caution_fee', models.IntegerField(default=0)),
                ('transport_fee', models.IntegerField(default=0)),
                ('iste_fee', models.IntegerField(default=0)),
                ('training_placement_fee', models.IntegerField(default=0)),
                ('college_festival_fee', models.IntegerField(default=0)),
                ('late_fee', models.IntegerField(default=0)),
                ('last_admission_date', models.DateField(null=True)),
                ('branch', models.ManyToManyField(to='jist_api.Branch')),
                ('depertment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment')),
            ],
        ),
    ]
