# Generated by Django 2.2.5 on 2019-11-16 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0030_auto_20191116_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='be_fee_table',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='depertment',
            field=models.ManyToManyField(to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='semester_fees',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='students',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('NULL', ''), ('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Fifth', 'V'), ('Sixth', 'VI'), ('Seventh', 'VII'), ('Eighth', 'VIII')], default='NULL', max_length=100)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Branch')),
                ('depertment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Students')),
            ],
        ),
    ]
