# Generated by Django 2.1 on 2019-12-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0032_auto_20191204_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_fee_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Even', 'EVEN'), ('Odd', 'ODD')], default='NULL', max_length=100)),
                ('regular_exam_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('compartmetal_exam_fee_practicle_one', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('compartmetal_exam_fee_practicle_more', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('compartmetal_exam_fee_no_practicle_one', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('compartmetal_exam_fee_no_practicle_more', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('betterment_exam_fee_one', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('betterment_exam_fee_more', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('non_college_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('depertment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment')),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Students'),
        ),
        migrations.AlterField(
            model_name='be_fee_table',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='depertment',
            field=models.ManyToManyField(to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='semester_fees',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='students',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
    ]
