# Generated by Django 2.1 on 2020-02-03 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jist_api', '0050_auto_20200130_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='NULL', max_length=100)),
                ('last_name', models.CharField(default='NULL', max_length=100)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('caste', models.CharField(choices=[('General', 'GENERAL'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('ST(H)', 'ST(H)')], default='NULL', max_length=100)),
                ('semester', models.CharField(choices=[('NULL', ''), ('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Fifth', 'V'), ('Sixth', 'VI'), ('Seventh', 'VII'), ('Eighth', 'VIII')], default='NULL', max_length=100)),
                ('admission_year', models.IntegerField(default=2020)),
                ('roll_number', models.CharField(default='NULL', max_length=100)),
                ('session', models.CharField(default='NULL', max_length=20)),
                ('father_name', models.CharField(default='NULL', max_length=100)),
                ('mother_name', models.CharField(default='NULL', max_length=100)),
                ('address', models.TextField(default='NULL', max_length=500)),
                ('parents_phone_number', models.CharField(default='NULL', max_length=20)),
                ('entry_type', models.CharField(choices=[('NULL', ''), ('Regular', 'Regular'), ('Lateral', 'Lateral')], default='Regular', max_length=20)),
                ('transfered_institute_name', models.CharField(default='NULL', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Students'),
        ),
        migrations.AlterField(
            model_name='be_fee_table',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='betterment_fee_table',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='betterment_fee_table',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Students'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='depertment',
            field=models.ManyToManyField(to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='compartmental_fee_table',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='compartmental_fee_table',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Students'),
        ),
        migrations.AlterField(
            model_name='exam_fee_table',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='examination_fee_table',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='examination_fee_table',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Students'),
        ),
        migrations.AlterField(
            model_name='semester_fees',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AlterField(
            model_name='students',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
        migrations.AddField(
            model_name='transfer_students',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Branch'),
        ),
        migrations.AddField(
            model_name='transfer_students',
            name='depertment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jist_api.Depertment'),
        ),
    ]
